### ISSUE TITLE
Adding Face Filter

### ISSUE THREAD

**Issue by moderateepheezy** [SimonCherryGZ/ARCamera#1]
Thanks for this wonderful project, Please can you guide me through how you added the face recognition filters you used.

**Comment by SimonCherryGZ** [comment]
Thanks. I'm glad you liked it.
This project is base on some true expert's open source project. You can find the link on the readme file. 
I suggest you to check it first, because I haven't quite understand it and still need to learn from it too.
And I still could give you some advice, maybe we can discuss it on some IM app?
Forgive my poor English:joy:.

**Comment by moderateepheezy** [comment]
I would love you to give me some advice, can we talk on WhatsApp?  or Facebook(https://www.facebook.com/abdulhafeeslawal)

**Comment by SimonCherryGZ** [comment]
I had been sent add friend request to you on Facebook.
